// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/myndlab/BuildComplete.tsx": () => import("../components/mockups/myndlab/BuildComplete.tsx"),
  "./components/mockups/myndlab/BuildProgress.tsx": () => import("../components/mockups/myndlab/BuildProgress.tsx"),
  "./components/mockups/myndlab/Dashboard.tsx": () => import("../components/mockups/myndlab/Dashboard.tsx"),
  "./components/mockups/myndlab/Landing.tsx": () => import("../components/mockups/myndlab/Landing.tsx"),
  "./components/mockups/myndlab/MyndlabFlow.tsx": () => import("../components/mockups/myndlab/MyndlabFlow.tsx"),
  "./components/mockups/myndlab/PromptExperience.tsx": () => import("../components/mockups/myndlab/PromptExperience.tsx"),
  "./components/mockups/myndlab/ShareApp.tsx": () => import("../components/mockups/myndlab/ShareApp.tsx"),
  "./components/mockups/myndlab/Signup.tsx": () => import("../components/mockups/myndlab/Signup.tsx")
};
